name: WDIO CI Github Action
on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Start local server
          run: |
              npm install -g http-server
              http-server -p 8000 &
        - uses: actions/setup-node@v1
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Test
          run: npm run test:local
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs